/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VotingPlatform } from "./VotingPlatform";
export * as factories from "./factories";
export { VotingPlatform__factory } from "./factories/VotingPlatform__factory";
